Update Dockerfile

diff --git a/api2/Dockerfile b/api2/Dockerfile
--- a/api2/Dockerfile
+++ b/api2/Dockerfile
@@ -1,13 +1,44 @@
-FROM python:2
+#FROM python:2
 
-MAINTAINER Alderano Fileni <afileni@hotmail.com>
+#MAINTAINER Alderano Fileni <afileni@hotmail.com>
 
-ADD api.py requirements.txt /
-RUN pip install -r ./requirements.txt
+#ADD api.py requirements.txt /
+#RUN pip install -r ./requirements.txt
 
-ENV PORT=5000
+#ENV PORT=5000
 
-EXPOSE $PORT
-HEALTHCHECK CMD curl --fail http://localhost:$PORT || exit 1
+#EXPOSE $PORT
+#HEALTHCHECK CMD curl --fail http://localhost:$PORT || exit 1
 
-CMD [ "./api.py" ]
+#CMD [ "./api.py" ]
+
+FROM tiangolo/uwsgi-nginx:python3.8
+
+LABEL maintainer="Sebastian Ramirez <tiangolo@gmail.com>"
+
+RUN pip install flask
+
+# URL under which static (not modified by Python) files will be requested
+# They will be served by Nginx directly, without being handled by uWSGI
+ENV STATIC_URL /static
+# Absolute path in where the static files wil be
+ENV STATIC_PATH /app/static
+
+# If STATIC_INDEX is 1, serve / with /static/index.html directly (or the static URL configured)
+# ENV STATIC_INDEX 1
+ENV STATIC_INDEX 0
+
+# Add demo app
+COPY ./app /app
+WORKDIR /app
+
+# Make /app/* available to be imported by Python globally to better support several use cases like Alembic migrations.
+ENV PYTHONPATH=/app
+
+# Move the base entrypoint to reuse it
+RUN mv /entrypoint.sh /uwsgi-nginx-entrypoint.sh
+# Copy the entrypoint that will generate Nginx additional configs
+COPY entrypoint.sh /entrypoint.sh
+RUN chmod +x /entrypoint.sh
+
+ENTRYPOINT ["/entrypoint.sh"]
